[package]
name = "todo-list-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
serde = "1.0.216"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
